Backend-Homework-Pronia/Models/Size.cs
using Backend_Homework_Pronia.Models.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Backend_Homework_Pronia.Models
{
    public class Size:BaseEntity
    {
        [Required, StringLength(maximumLength: 35)]

        public string Name { get; set; }
        //public List<PlantSize> PlantSizes { get; set; }
        //public int ColorId { get; set; }
        //public Color Color { get; set; }
        public List<ColorSize> ColorSizes { get; set; }


    }
}

Backend-Homework-Pronia/Areas/ProniaAdmin/Controllers/SizeController.cs
using Backend_Homework_Pronia.DAL;
using Backend_Homework_Pronia.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Backend_Homework_Pronia.Areas.ProniaAdmin.Controllers
{
    [Area("ProniaAdmin")]
    public class SizeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SizeController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Size> model = _context.Sizes.ToList();
            return View(model);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(Size size)
        {
            if (!ModelState.IsValid) return View();
            Size existed = _context.Sizes.FirstOrDefault(x =>
            x.Name.ToLower().Trim() == size.Name.ToLower().Trim());
            if (existed != null)
            {
                ModelState.AddModelError("Name", "This size already exists");
                return View();
            }
            _context.Sizes.Add(size);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int? id)
        {
            if (id is null || id == 0) return NotFound();

            Size existed = _context.Sizes.FirstOrDefault(x => x.Id == id);
            if (existed is null) return NotFound();

            return View(existed);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Edit(int? id, Size newSize)
        {
            if (id is null || id == 0) return NotFound();
            if (!ModelState.IsValid) return View();

            Size existed = _context.Sizes.FirstOrDefault(x => x.Id == id);
            if (existed is null) return BadRequest();

            bool isDuplicate = _context.Sizes.Any(x => x.Name.ToLower().Trim() == newSize.Name.ToLower().Trim());
            if (isDuplicate)
            {
                ModelState.AddModelError("Name", "This size already exists");
                return View();
            }

            _context.Entry(existed).CurrentValues.SetValues(newSize);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Remove(int? id)
        {
            if (id is null || id == 0) return NotFound();

            Size size = await _context.Sizes.FirstOrDefaultAsync(x => x.Id == id);

            if (size is null) return NotFound();

            _context.Sizes.Remove(size);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Detail(int? id)
        {
            if (id is null || id == 0) return NotFound();

            Size existed = _context.Sizes.FirstOrDefault(x => x.Id == id);

            if (existed is null) return NotFound();
            return View(existed);
        }
    }
}

Backend-Homework-Pronia/Areas/ProniaAdmin/Views/Size/Create.cshtml
@model Size
@{
    ViewData["Title"] = "Create";
}


<div class="main-panel">
    <h1>Create a size</h1>
    <form class="mt-3" method="post" enctype="multipart/form-data">
        <div>
            <label>Size name:</label><br />
            <input asp-for="Name" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>

        <div class="mt-2">
            <button class="btn btn-success" type="submit">Create</button>
        </div>
    </form>
</div>

Backend-Homework-Pronia/Areas/ProniaAdmin/Views/Size/Detail.cshtml
@model Size
@{
    ViewData["Title"] = "Detail";
}

<div>
    <h3>Details of Size</h3>
    <p>Id: @Model.Id</p>
    <p>Size: @Model.Name</p>
</div>

Backend-Homework-Pronia/Areas/ProniaAdmin/Views/Size/Edit.cshtml
@model Size
@{
    ViewData["Title"] = "Edit";
}


<div class="main-panel d-flex flex-column justify-content-center align-items-center">
    <h1>Edit size</h1>
    <form class="mt-3" method="post">
        <div>
            <label>Size name:</label><br />
            <input asp-for="Name" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
        <div class="mt-2">
            <button class="btn btn-warning" type="submit">Edit</button>
        </div>
    </form>
</div>

Backend-Homework-Pronia/Areas/ProniaAdmin/Views/Size/Index.cshtml
@model List<Size>
@{
    ViewData["Title"] = "Index";
}

<div class="main-panel">
    <div>
        <a asp-area="proniaadmin" asp-controller="Size" asp-action="Create" class="btn btn-outline-success">Create new color</a>
    </div>
    <div class="table-responsive pt-3">
        <table class="table table-dark">
            <thead>
                <tr>

                    <th>
                        Id
                    </th>
                    <th>
                        Name
                    </th>

                    <th>
                        Settings
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (Size size in Model.OrderByDescending(x => x.Id))
                {
                    <tr>

                        <td> @size.Id </td>

                        <td>@size.Name</td>

                        <td class="d-flex ">
                            <div class="me-2">
                                <a asp-area="ProniaAdmin" asp-controller="size" asp-action="Edit" asp-route-id="@size.Id" class="btn btn-outline-warning">
                                    <i class="mdi mdi-border-color"></i>
                                </a>
                            </div>
                            <div class="me-2">
                                <a asp-area="ProniaAdmin" asp-controller="size" asp-action="Remove" asp-route-id="@size.Id" class="btn btn-outline-danger">
                                    <i class="mdi mdi-delete"></i>
                                </a>
                            </div>
                            <div>
                                <a asp-area="ProniaAdmin" asp-controller="size" asp-action="Detail" asp-route-id="@size.Id" class="btn btn-outline-info">
                                    <i class="mdi mdi-comment-question-outline"></i>
                                </a>
                            </div>
                        </td>

                    </tr>
                }

            </tbody>
        </table>
    </div>

</div>